#!/usr/bin/env zsh

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
  print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
  command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
  command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
    print -P "%F{33} %F{34}Installation successful.%f%b" || \
    print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

### "command not found: compdef" 対策
autoload -Uz compinit
compinit
###

### 分割ファイルの読み込み
ZSHHOME="${HOME}/.zsh"

if [ -d $ZSHHOME -a -r $ZSHHOME -a -x $ZSHHOME ]; then
  for i in $ZSHHOME/*; do
    [[ ${i##*/} = *.zsh ]] &&
    [ \( -f $i -o -h $i \) -a -r $i ] && . $i
  done
fi
###

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
  zdharma-continuum/zinit-annex-as-monitor \
  zdharma-continuum/zinit-annex-bin-gem-node \
  zdharma-continuum/zinit-annex-patch-dl \
  zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

### Start original custom
eval "$(starship init zsh)"

zinit light asdf-vm/asdf

zinit ice as"program" from"gh-r" \
  mv"jq-* -> jq" \
  pick"jq" \
  bpick"jq-linux64"
zinit light jqlang/jq

if [[ $(uname) == "Darwin" && $(uname -m) == "x86_64" ]]; then
  zinit ice as"program" from"gh-r" \
    pick"fzf" \
    bpick"fzf-*-darwin_amd64.zip"
  zinit light junegunn/fzf

  zinit ice as"program" from"gh-r" \
    pick"kustomize" \
    ver"kustomize/v4.5.7" \
    bpick"kustomize_*_darwin_amd64.tar.gz"
  zinit light kubernetes-sigs/kustomize

  zinit ice as"program" from"gh-r" \
    pick"kubeseal" \
    bpick"kubeseal-*-darwin-amd64.tar.gz"
  zinit light bitnami-labs/sealed-secrets

  # golang が必要
  zinit ice as"program" \
    atclone"cd helm" \
    atpull"%atclone" \
    make \
    pick"bin/helm"
  zinit light helm/helm

  zinit ice as"program" from"gh-r" \
    pick"gh_*/bin/gh" \
    bpick"gh_*_macOS_amd64.tar.gz"
  zinit light cli/cli

  zinit ice as"program" from"gh-r" \
    pick"jsonnet" \
    pick"jsonnetfmt" \
    bpick"go-jsonnet_*_Darwin_x86_64.tar.gz"
  zinit light google/go-jsonnet

  zinit ice as"program" from"gh-r" \
    pick"bin/darwin_amd64/kubelogin" \
    bpick"kubelogin-darwin-amd64.zip"
  zinit light Azure/kubelogin
fi

zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions

zinit load atusy/gh-fzf
zinit load migutw42/zsh-fzf-ghq

export PATH=$HOME/bin:$PATH
